### ISSUE TITLE
Zeilen entfernen bei leerem Platzhalter

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-client#114]
Forum:
Platzhalter
Schließlich eine kleine Anregung - die Vorlagen unterscheiden nicht, ob einen Platzhalter definiert ist oder nicht. Das führt dazu, dass man unterschiedliche Vorlagen für Firmen und Privatpersonen anlegen muss, weil anderenfalls Lehrzeilen im Andressenfeld entstehen. Das gleiche gilt eigentlich für die "Vorab per Fax"-Zeile, wenn keine Faxnummer hinterlegt wurde. Die Zeile muss dann immer per Hand entfernt werden, was nicht allzu tragisch ist, aber halt umständig.
Antwort Jens:
Das schaue ich mir mal an. Das heisst, wenn der Platzhalter der einzige Inhalt einer Zeile ist, dann wäre die Zeile zu entfernen. Das würde dann natürlich bedeuten, daß das Layout der Vorlage verändert würde. Ich nehme das mit in die Featureplanung auf und werde es vorher mit einigen anderen Anwendern besprechen.

**Comment by j-dimension** [comment]
@RasimT

**Comment by j-dimension** [comment]
Erledigt

**Comment by j-dimension** [comment]
Test: geht noch nicht bei allen Layouts. Bsp: leere Strasse in Mandantenadresse, Vorlage j-lawyer-allgemeines-Schreiben-Mandant

**Comment by RasimT** [comment]
Perfekt! Bis wann rechnen Sie mit einem Update? lg aus bodŕum


vgl. Anlage___________________________________Rechtsanwalt TosunFachanwalt für Mietrecht undWohnungseigentumsrechtSonnenstr. 27 | 72458 Albstadtwww.kanzlei-albstadt.de

-------- Ursprüngliche Nachricht --------Von: Jens Kutschke <notifications@github.com> Datum: 30.07.18  22:18  (GMT+03:00) An: jlawyerorg/j-lawyer-client <j-lawyer-client@noreply.github.com> Cc: RasimT <tosun@kanzlei-albstadt.de>, Mention <mention@noreply.github.com> Betreff: Re: [jlawyerorg/j-lawyer-client] Zeilen entfernen bei leerem Platzhalter (#114) 
Closed #114.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jlawyerorg/j-lawyer-client","title":"jlawyerorg/j-lawyer-client","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/jlawyerorg/j-lawyer-client"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #114."}],"action":{"name":"View Issue","url":"https://github.com/jlawyerorg/j-lawyer-client/issues/114#event-1761012403"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jlawyerorg/j-lawyer-client/issues/114#event-1761012403",
"url": "https://github.com/jlawyerorg/j-lawyer-client/issues/114#event-1761012403",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [jlawyerorg/j-lawyer-client] Zeilen entfernen bei leerem Platzhalter (#114)",
"sections": [
{
"text": "",
"activityTitle": "**Jens Kutschke**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@j-dimension",
"facts": [

]
}
],
"potentialAction": [
{
"targets": [
{
"os": "default",
"uri": "https://github.com/jlawyerorg/j-lawyer-client/issues/114#event-1761012403"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 308085969\n}"
}
],
"themeColor": "26292E"
}
]
