### ISSUE TITLE
Installation auf Debian mit MariaDB

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-client#192]

**Comment by nullproblemo** [comment]
@githubnullproblemo

**Comment by j-dimension** [comment]
mit Debian 9.5.0, frisches "Netinst"-Image mit GNOME:

(als root - via "su")
- apt install sudo
- adduser <nutzerid> sudo (erfordert neues Login)
- apt install mariadb-server --> installiert MariaDB ohne Passwortauthentifzierung für root
- sudo mysql -u root
- use mysql;
update user set plugin='' where User='root';
flush privileges;
quit;
- sudo systemctl restart mariadb.service
- sudo mysql_secure_installation
    Enter current password for root (enter for none): Enter
    Set root password? [Y/n]: Y
    New password: Enter password
    Re-enter new password: Repeat password
    Remove anonymous users? [Y/n]: Y
    Disallow root login remotely? [Y/n]: Y
    Remove test database and access to it? [Y/n]:  Y
    Reload privilege tables now? [Y/n]:  Y
- sudo mysql -u root -p

Installationsanleitung Linux angepasst:
https://www.j-lawyer.org/?page_id=93

**Comment by nullproblemo** [comment]
Hi,
bei mir war nach dem Befehl

> Enter current password for root (enter for none): Enter

bereits Schluss. Statt mit "Enter" habe ich es mit dem bereits vorhandenen Passwort versucht, dann aber die Finger davon gelassen und mein System sicherheitshalber mit Clonezilla zurückgesetzt:
root@didi:/home/didi# apt install mariadb-server
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Die folgenden NEUEN Pakete werden installiert:
  mariadb-server
0 aktualisiert, 1 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Es müssen 26,2 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 63,5 kB Plattenplatz zusätzlich benutzt.
Holen:1 http://security.debian.org stretch/updates/main amd64 mariadb-server all 10.1.26-0+deb9u1 [26,2 kB]
Es wurden 26,2 kB in 0 s geholt (207 kB/s).
Vormals nicht ausgewähltes Paket mariadb-server wird gewählt.
(Lese Datenbank ... 365036 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../mariadb-server_10.1.26-0+deb9u1_all.deb ...
Entpacken von mariadb-server (10.1.26-0+deb9u1) ...
mariadb-server (10.1.26-0+deb9u1) wird eingerichtet ...
root@didi:/home/didi# sudo mysql -u root
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 2
Server version: 10.1.26-MariaDB-0+deb9u1 Debian 9.1

Copyright (c) 2000, 2017, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> use mysql;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [mysql]> update user set plugin='' where User='root';
Query OK, 1 row affected (0.00 sec)
Rows matched: 1  Changed: 1  Warnings: 0

MariaDB [mysql]> flush privileges;
Query OK, 0 rows affected (0.00 sec)

MariaDB [mysql]> quit;
Bye
root@didi:/home/didi# sudo systemctl restart mariadb.service
root@didi:/home/didi# sudo mysql_secure_installation

NOTE: RUNNING ALL PARTS OF THIS SCRIPT IS RECOMMENDED FOR ALL MariaDB
      SERVERS IN PRODUCTION USE!  PLEASE READ EACH STEP CAREFULLY!

In order to log into MariaDB to secure it, we'll need the current
password for the root user.  If you've just installed MariaDB, and
you haven't set the root password yet, the password will be blank,
so you should just press enter here.

Enter current password for root (enter for none): 
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
Enter current password for root (enter for none): 
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
Enter current password for root (enter for none): 
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
Enter current password for root (enter for none): 
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
Enter current password for root (enter for none): 
OK, successfully used password, moving on...

Setting the root password ensures that nobody can log into the MariaDB
root user without the proper authorisation.

You already have a root password set, so you can safely answer 'n'.

Change the root password? [Y/n] n
 ... skipping.

By default, a MariaDB installation has an anonymous user, allowing anyone
to log into MariaDB without having to have a user account created for
them.  This is intended only for testing, and to make the installation
go a bit smoother.  You should remove them before moving into a
production environment.

Remove anonymous users? [Y/n]

**Comment by j-dimension** [comment]
Dann hat Deine MariaDB bereits ein root-Passwort und wäre somit bereits "ready" für eine j-lawyer.org-Serverinstallation.

**Comment by j-dimension** [comment]
Ich habe meine Tests wie beschrieben auf eine "frische" Debian 9.5.0-Installation aufgesetzt.

**Comment by nullproblemo** [comment]
Ich habe die Installation durchführen können, mit der Maßgabe des manuellen Starts/Stopps Doch der Server lässt sich nicht starten, so dass ich auch keine Verbindung über den Client erhalte:
didi@didi:~$ cd /opt/j-lawyer-server
didi@didi:/opt/j-lawyer-server$ sudo -u j-lawyer-server sh start-server.sh
sudo: Unbekannter Benutzer: j-lawyer-server
sudo: Regelwerks-Plugin konnte nicht initialisiert werden
didi@didi:/opt/j-lawyer-server$

**Comment by j-dimension** [comment]
Der Nutzer "j-lawyer-server" wird nur angelegt, wenn man sich entscheidet als Dienst zu installieren. 

Für einen Test kannst Du den Server mal als root starten. Für einen normalen Betrieb würde ich dann entweder den Dienst nachinstallieren oder einen eigenen Nutzer anlegen, unter welchem man manuell startet.

**Comment by nullproblemo** [comment]
Als Dienst klappt die Installation. Nur, wenn ich den manuellen Weg gehe, scheitere ich nach Deiner Anleitung: https://www.j-lawyer.org/?page_id=93
(4) Start des Servers
Bei Installation als Dienst: nach erfolgreicher Installation läuft der Dienst bereits. Der Dienst kann mit „sudo service j-lawyer-server stop“ gestoppt und mit „sudo service j-lawyer-server start“ gestartet werden.
Bei manuellem Start/Stopp: „sudo -u j-lawyer-server sh start-server.sh“ im Verzeichnis /opt/j-lawyer-server ausführen, Herunterfahren durch Abbrechen des Prozesses mit Strg+C.

Ich entferne mal die derzeitige Installation. Falls Du Lust hast, kannst Du mich abends anrufen und wir spielen das per Teamviewer durch.

**Comment by j-dimension** [comment]
Ich habe die von Dir verlinkte Anleitung aktualisiert: Anlegen eines eigenen Nutzers und Rechtevergabe auf den relevanten Verzeichnissen. 

Teamviewer-Sitzung können wir gern machen wenn Not am Mann ist :-)

**Comment by nullproblemo** [comment]
Not ist nicht am Mann. Ich dachte nur, es könnte ein Bug vorliegen, der per Teamviewer einfacher zu eruieren wäre. Ich habe jetzt entsprechend Deiner Aktualisierung den Server für manuellen Start/Stopp installiert. j-lawyer startet mit admin + a einwandfrei. Nach der Installation des Servers kamen die elend langen Meldungen der angehängten Datei "manuell1". Ich habe das Programm zudem beenden müssen, weil im weiteren geöffneten Terminal, mit dem ich den Client installieren wollte, beim Befehl "chmod a+x j-lawyer-client_unix_1_9_0.sh" laut Konsolenausgabe eben diese Datei merkwürdigerweise nicht gefunden werden konnte. Erst, nachdem ich den Server beendet hatte, ließ sich der Client installieren. Ich habe danach den Server wieder und auch den Client gestartet. Den Server habe ich mit Strg. + c angehalten Die Konsolenausgabe habe ich der Datei "manuell2" beigefügt. Ist das, was da ausgegeben wurde, so in Ordnung?
[manuell1.txt](https://github.com/jlawyerorg/j-lawyer-client/files/2380782/manuell1.txt)
[manuell2.txt](https://github.com/jlawyerorg/j-lawyer-client/files/2380784/manuell2.txt)

**Comment by nullproblemo** [comment]
Vielleicht könntest Du erklären, was Du in der Rubrik "Debian 9 mit MariaDB statt MySQL", "MariaDB wird in den Voreinstellungen ohne Passwort für den Datenbanknutzer „root“ installiert. Man sichert die Installation wie folgt ab" genau gemacht hast. Ich kann die Befehle zwar kopieren, doch inhaltlich sagen sie mir nichts.

**Comment by j-dimension** [comment]
Ich habe in der Anleitung nun folgendes Statement zu den Befehlen hinzugefügt: 

"Dabei verbindet man sich (ohne Passwort) zur Datenbank, wechselt in die "mysql"-Datenbank, aktiviert passwortbasierte Authentifizierung, lädt die Änderungen neu, verlässt die Datenbank und startet den MariaDB-Service neu."

**Comment by j-dimension** [comment]
@nullproblemo ja, beide Logdateien sehen sauber aus - der Dienst startet korrekt. 

Und ja, er ist sehr gesprächig :-)

**Comment by nullproblemo** [comment]
Ok. Ich hatte schon bedenken, dass MariaDB ev. so verändert (abgesichert) wurde, dass bei anderen installierten oder später zu installierenden Anwedungen Probleme auftreten könnten. Dann ist ja alles supergut!

**Comment by j-dimension** [comment]
Nein, keine Probleme zu erwarten. Passwort der DB aber gut (und sicher) aufbewahren!
